### ISSUE TITLE
choice of random.seed and boot.num for npsigtest

### ISSUE THREAD

**Issue by waynelapierre** [JeffreyRacine/R-Package-np#30]
Are there any specific reasons to choose 42 and 399 as npsigtest's default random.seed and boot.num? If I use 1 and 500 instead, would that be a problem?

**Comment by JeffreyRacine** [comment]
Hi Wayne,

You can use any seed you want... 42 has special meaning to Douglas Adams fans ;-). re: 399 versus 500... for inference you need to be careful otherwise size will not be correct, and you need \alpha*(B+1) to be an integer where alpha is nominal size (e.g. 0.05) and B the number of bootstrap replications...plus there are power trade-offs as B changes so 399 is seen as a good compromise: see http://econ.queensu.ca/faculty/mackinnon/papers/many.pdf and related publications

**Comment by waynelapierre** [comment]
thanks so much for the clarification!
