### ISSUE TITLE
npsigtest slow

### ISSUE THREAD

**Issue by waynelapierre** [JeffreyRacine/R-Package-np#40]
Is there any way to make npsigtest faster? I have an R script where more than 95% of the time is spent on multiple npsigtest functions.

**Comment by JeffreyRacine** [comment]
Hi,

Thanks for your interest in the package. You could try the option ckertype=”epanechnikov” in the call to the bandwidth generation and the call to npsigtest, plus set the global option option(np.tree=TRUE) (see FAQ for a tad more info), and drop the number of bootstrap reps to 99 from 399… see if that helps?

**Comment by waynelapierre** [comment]
Does dropping the number of bootstrap reps make the result less reliable? Thanks.

**Comment by JeffreyRacine** [comment]
Hi,
 
Slight reduction in power, that’s all… size unaffected…

 
Jeff
 

From: waynelapierre ***@***.***>
Reply-To: JeffreyRacine/R-Package-np ***@***.***>
Date: Friday, October 14, 2022 at 21:29
To: JeffreyRacine/R-Package-np ***@***.***>
Cc: "Racine, Jeffrey" ***@***.***>, State change ***@***.***>
Subject: Re: [JeffreyRacine/R-Package-np] npsigtest slow (Issue #40)


 

Does dropping the number of bootstrap reps make the result less reliable? Thanks.
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you modified the open/close state.Message
 ID: ***@***.***>
