### ISSUE TITLE
Question about citation 

### ISSUE THREAD

**Issue by waynelapierre** [JeffreyRacine/R-Package-np#43]
Why there are both Racine and Li (2004) and Li and Racine  (2004) on the np package manual? Shouldn't they be Li and Racine  (2004 a; 2004 b) or Racine and Li  (2004 a; 2004 b) if a consistent citation style is used?

**Comment by JeffreyRacine** [comment]
Hi,

Because this is the author order in the printed versions. So if you download the  bibtex citations from the publishers one appears as Racine & Li (2004), the other as Li & Racine (2004)... so one would be correctly referred to as Racine et al (2004) and the other Li et al (2004). Hope this helps!
