### ISSUE TITLE
Bandwidth matrix

### ISSUE THREAD

**Issue by EfthymiosCosta** [JeffreyRacine/R-Package-np#49]
Dear Jeffrey,

I was wondering if there is currently an implementation of multivariate kernel density estimation which does not assume independence of variables (thus not using a kernel product approach). For instance, given data $` \boldsymbol{X}_1, \ldots,  \boldsymbol{X}_n \in \mathbb{R}^p `$, the multivariate kernel would be:

$` \hat{f}(\boldsymbol{x}, \boldsymbol{H}) = \frac{1}{n \lvert H \rvert ^{1/2}} \sum_{i=1}^n K_{\boldsymbol{H}}\left( \boldsymbol{H}^{-\frac{1}{2}}(\boldsymbol{x} - \boldsymbol{X}_i)\right), `$
where $\boldsymbol{H}$ is a bandwidth matrix that is not necessarily diagonal (as is the case when using the kernel product approach). Is this something that is implemented in the `np` package or would you consider adding this if not?

Thanks!

**Comment by JeffreyRacine** [comment]
Greetings Efthymios,

Thanks for your interest in the package.

Two things (2. may simply be wording but bears stating (re: "independence"))

1. No, multivariate kernels with a lower diagonal bandwidth matrix of dimension d*(d+1)/2 are not supported

2. However, kindly note that it is definitely **not** the case that the use of product kernel functions imposes independence among variables as you write (a not uncommon misconception). If this was the case the marginals would be equal for a variable regardless of the values taken on by others, which is clear not the case. 

Consider the following simple example:

    library(np)
    options(plot.par.mfrow=FALSE)
    data(faithful)
    par(mfrow=c(3,2))
    plot(eruptions~waiting,data=faithful)
    f <- npudens(~waiting+eruptions,data=faithful)
    plot(f,view="fixed",phi=70,xtrim=-0.05,ytrim=-0.05)

Clearly here, even though we use product kernels, they have completely captured the conditional dependence structure among the two variables... now let's see if we used the product of the two univariate kernel density estimates (which **would** presume independence):

    waiting.seq <- seq(40,100,length=50)
    eruptions.seq <- seq(1,6,length=50)
    grid <- expand.grid(waiting=waiting.seq,eruptions=eruptions.seq)
    f.waiting <- npudens(tdat=faithful$waiting,edat=grid$waiting)
    f.eruptions <- npudens(tdat=faithful$eruptions,edat=grid$eruptions)
    plot(f.eruptions,xlab="eruptions")
    plot(f.waiting,ylab="waiting")
    f.independent <- fitted(f.waiting)*fitted(f.eruptions)
    persp(waiting.seq,eruptions.seq,
          matrix(f.independent,nrow=50,ncol=50),
          theta=30,
          phi=70,
          ticktype="detailed",
          xlab="eruptions",
          ylab="waiting",
          zlab="f(waiting)xf(eruptions)")

Hopefully you can see that the estimate using the product kernel (upper right figure) and that presuming independence (lower left figure) do not coincide, and that the lower left figure has marginals which are independent while the upper right does not. So, to summarize, the use of product kernel functions definitely **does not** impose nor imply independence in this setting - the kernel is simply a smoothing function, product or otherwise (i.e., the estimate inherits smoothness from the kernel, nothing else).

Hope this helps!

**Comment by EfthymiosCosta** [comment]
Hi Jeffrey,

Thanks a lot for your answer, it's very much appreciated! I was wondering if there are any references you would recommend highlighting and potentially proving the 2nd point - that is that using product kernel functions does not impose independence among variables.

Thanks,
Efthymios

**Comment by JeffreyRacine** [comment]
Greetings Efthymios,

Most welcome. On page 87 of the book

https://www.cambridge.org/br/universitypress/subjects/economics/econometrics-statistics-and-mathematical-economics/introduction-advanced-theory-and-practice-nonparametric-econometrics-replicable-approach-using-r?format=HB

you will find the following sentence:

"One popular choice of kernel function is the *product kernel*, which is simply a product of univariate kernel functions. [...] We might be tempted to believe that using a product kernel function somehow imposes or assumes independence since $f(y,x)=f(y)\times f(x)$ if and only $y$ and $x$ are independent. However, this would be incorrect. The kernel function is simply a weighting device that imparts smoothness on the resulting estimate, with the bandwidths determining how much smoothing is applied to each component. As long as the kernel function is non-negative and it integrates to one over all of its arguments, then a proper and consistent estimator can emerge if smoothing is conducted appropriately."

Citation would be Page 86-87

    @book{RACINE:2019,
    TITLE = "An Introduction to the Advanced Theory and Practice of Nonparametric Econometrics",
    AUTHOR = "Racine, J.",
    YEAR = "2019", 
    PUBLISHER = "Cambridge University Press"}

Hope this helps!

Jeff
